/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service info
         * @description Returns a plain-text message confirming the service is running.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is running. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                            uptimeSeconds: number;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (alias for /health) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                            uptimeSeconds: number;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI spec (JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI 3.0.3 spec as JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interactive API documentation (Swagger UI) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swagger UI HTML page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/last-modified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last data import timestamp */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Timestamp of the most recent data import. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @description ISO 8601 timestamp, or null if no import has run.
                             */
                            lastModified?: string | null;
                        };
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all teams. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available seasons (defaults to regular) */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of seasons that have data. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available seasons for a report type */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of seasons that have data for the given report type. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/season/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player stats for the latest available season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Player"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/season/{reportType}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player stats for a specific season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                    /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
                    season: components["parameters"]["season"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Player"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/combined/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player stats combined across all seasons
         * @description Returns each player's stats aggregated across all seasons (from 2012-2013 onwards).
         *     Each entry includes a `seasons` array with per-season stats and scores.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Combined player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CombinedPlayer"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/season/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Goalie stats for the latest available season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goalie"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/season/{reportType}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Goalie stats for a specific season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                    /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
                    season: components["parameters"]["season"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goalie"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/combined/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Goalie stats combined across all seasons
         * @description Returns each goalie's stats aggregated across all seasons (from 2012-2013 onwards).
         *     `gaa` and `savePercent` are omitted when `reportType=both` (cannot be combined reliably).
         *     Each entry includes a `seasons` array with per-season stats.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Combined goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CombinedGoalie"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/playoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-time playoff leaderboard
         * @description Returns each team's all-time playoff record sorted by best result.
         *     Includes `tieRank: true` when the entry's record matches the previous entry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playoff leaderboard entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayoffLeaderboardEntry"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/regular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-time regular season leaderboard
         * @description Returns each team's all-time regular season record aggregated across all seasons,
         *     sorted by total points then total wins.
         *     Includes `tieRank: true` when the entry's record matches the previous entry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Regular season leaderboard entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegularLeaderboardEntry"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Team: {
            /** @example 1 */
            id: string;
            /** @example colorado */
            name: string;
            /** @example Colorado Avalanche */
            presentName: string;
            nameAliases?: string[];
            /**
             * @description First season year (YYYY) for expansion/relocated teams.
             * @example 2017
             */
            firstSeason?: number;
        };
        Season: {
            /** @example 2023 */
            season: number;
            /** @example 2023-2024 */
            text: string;
        };
        Player: {
            name: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            plusMinus: number;
            penalties: number;
            shots: number;
            ppp: number;
            shp: number;
            hits: number;
            blocks: number;
            /** @description Composite score (0-100 range). */
            score: number;
            /** @description Score adjusted by games played. */
            scoreAdjustedByGames: number;
            /** @description Per-stat score breakdown. */
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        Goalie: {
            name: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            penalties: number;
            ppp: number;
            shp: number;
            wins: number;
            saves: number;
            shutouts: number;
            /** @description Goals against average. Omitted for `reportType=both`. */
            gaa?: string;
            /** @description Save percentage. Omitted for `reportType=both`. */
            savePercent?: string;
            score: number;
            scoreAdjustedByGames: number;
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        PlayerSeasonData: components["schemas"]["Player"] & {
            season: number;
        };
        GoalieSeasonData: components["schemas"]["Goalie"] & {
            season: number;
        };
        CombinedPlayer: components["schemas"]["Player"] & {
            seasons: components["schemas"]["PlayerSeasonData"][];
        };
        CombinedGoalie: components["schemas"]["Goalie"] & {
            seasons: components["schemas"]["GoalieSeasonData"][];
        };
        PlayoffLeaderboardEntry: {
            teamId: string;
            teamName: string;
            /** @description Total playoff appearances (sum of championships, finals, conferenceFinals, secondRound, and firstRound). */
            appearances: number;
            championships: number;
            finals: number;
            conferenceFinals: number;
            secondRound: number;
            firstRound: number;
            /** @description True when this entry's record matches the previous entry's record. */
            tieRank: boolean;
        };
        RegularLeaderboardEntry: {
            teamId: string;
            teamName: string;
            seasons: number;
            wins: number;
            losses: number;
            ties: number;
            points: number;
            divWins: number;
            divLosses: number;
            divTies: number;
            winPercent: number;
            divWinPercent: number;
            /** @description Achieved points as a fraction of the maximum possible points (wins×2 + ties) / (games×2). */
            pointsPercent: number;
            /** @description Number of seasons the team finished rank 1 in regular standings. */
            regularTrophies: number;
            /** @description True when this entry's record matches the previous entry's record. */
            tieRank: boolean;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description Report dataset. `regular` and `playoffs` return the corresponding
         *     dataset. `both` merges regular + playoffs stats then calculates scores.
         */
        reportType: "regular" | "playoffs" | "both";
        /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
        season: number;
        /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
        teamId: string;
        /**
         * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
         *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
         */
        startFrom: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
