/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service info
         * @description Returns a plain-text message confirming the service is running.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is running. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                            uptimeSeconds: number;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (alias for /health) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                            uptimeSeconds: number;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI spec (JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI 3.0.3 spec as JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interactive API documentation (Swagger UI) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swagger UI HTML page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/last-modified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last data import timestamp */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Timestamp of the most recent data import. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @description ISO 8601 timestamp, or null if no import has run.
                             */
                            lastModified?: string | null;
                        };
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all teams. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available seasons (defaults to regular) */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of seasons that have data. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available seasons for a report type */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of seasons that have data for the given report type. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Season"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/season/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player stats for the latest available season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Player"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/season/{reportType}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player stats for a specific season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                    /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
                    season: components["parameters"]["season"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Player"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/combined/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player stats combined across all seasons
         * @description Returns each player's stats aggregated across all seasons (from 2012-2013 onwards).
         *     Each entry includes a `seasons` array with per-season stats and scores.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Combined player stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CombinedPlayer"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/season/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Goalie stats for the latest available season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goalie"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/season/{reportType}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Goalie stats for a specific season */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                    /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
                    season: components["parameters"]["season"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goalie"][];
                    };
                };
                /** @description Invalid report type or season not available. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goalies/combined/{reportType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Goalie stats combined across all seasons
         * @description Returns each goalie's stats aggregated across all seasons (from 2012-2013 onwards).
         *     `gaa` and `savePercent` are omitted when `reportType=both` (cannot be combined reliably).
         *     Each entry includes a `seasons` array with per-season stats.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
                    teamId?: components["parameters"]["teamId"];
                    /**
                     * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
                     *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
                     */
                    startFrom?: components["parameters"]["startFrom"];
                };
                header?: never;
                path: {
                    /**
                     * @description Report dataset. `regular` and `playoffs` return the corresponding
                     *     dataset. `both` merges regular + playoffs stats then calculates scores.
                     */
                    reportType: components["parameters"]["reportType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Combined goalie stats array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CombinedGoalie"][];
                    };
                };
                /** @description Invalid report type. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/career/player/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Career stats for one player
         * @description Returns all imported career records for a single Fantrax player ID across all fantasy teams.
         *     Zero-game rows are included and count toward `owned` totals but not `played` totals.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Fantrax player or goalie identifier. */
                    id: components["parameters"]["careerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Career stats document for one player. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerPlayer"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Player not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/career/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Career player list
         * @description Returns one summary row per player across all fantasy teams.
         *     Zero-game rows count toward owned seasons and teams, but not played counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Career player list entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerPlayerListItem"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/career/goalie/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Career stats for one goalie
         * @description Returns all imported career records for a single Fantrax goalie ID across all fantasy teams.
         *     Zero-game rows are included and count toward `owned` totals but not `played` totals.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Fantrax player or goalie identifier. */
                    id: components["parameters"]["careerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Career stats document for one goalie. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerGoalie"];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Goalie not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/career/goalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Career goalie list
         * @description Returns one summary row per goalie across all fantasy teams.
         *     Zero-game rows count toward owned seasons and teams, but not played counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Career goalie list entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerGoalieListItem"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/career/highlights/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Career highlights leaderboard
         * @description Returns a paged mixed skater + goalie career highlights leaderboard.
         *     `most-teams-played` and `most-teams-owned` return team-count rows.
         *     `same-team-seasons-played` and `same-team-seasons-owned` return one row per top team, so the same person can appear multiple times on tied same-team results.
         *     `most-stanley-cups` returns one row per player/goalie with cup seasons and fantasy teams.
         *     `reunion-king` returns one row per top reunion team, so the same person can appear multiple
         *     times on tied reunion results, and includes stint ranges for each return.
         *     `stash-king` returns the top same-team zero-game season counts, similar to
         *     `same-team-seasons-owned` but counting only team seasons where both regular and playoff
         *     games stayed at zero.
         *     `regular-grinder-without-playoffs` returns total regular-season games plus the played fantasy teams
         *     for players/goalies who never recorded a playoff appearance.
         *     Minimum cutoffs are 4 teams for `most-teams-played`, 5 teams for `most-teams-owned`,
         *     8 same-team seasons for `same-team-seasons-played`, 10 same-team seasons for
         *     `same-team-seasons-owned`, 2 cups for `most-stanley-cups`, 2 reunion stints for
         *     `reunion-king`, 10 stash counts for `stash-king`, and 60 games for
         *     `regular-grinder-without-playoffs`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of rows to skip from the start of the sorted highlight list. Defaults to `0`. */
                    skip?: components["parameters"]["skip"];
                    /** @description Number of rows to return from the sorted highlight list. Defaults to `10`. Maximum `100`. */
                    take?: components["parameters"]["take"];
                };
                header?: never;
                path: {
                    /** @description Career highlight leaderboard type. */
                    type: components["schemas"]["CareerHighlightType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged career highlight results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerTeamCountHighlightPage"] | components["schemas"]["CareerSameTeamHighlightPage"] | components["schemas"]["CareerStanleyCupHighlightPage"] | components["schemas"]["CareerReunionHighlightPage"] | components["schemas"]["CareerStashHighlightPage"] | components["schemas"]["CareerRegularGrinderHighlightPage"];
                    };
                };
                /** @description Invalid highlight type or paging params. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/playoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-time playoff leaderboard
         * @description Returns each team's all-time playoff record sorted by best result.
         *     Includes `tieRank: true` when the entry's record matches the previous entry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playoff leaderboard entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayoffLeaderboardEntry"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/regular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-time regular season leaderboard
         * @description Returns each team's all-time regular season record aggregated across all seasons,
         *     sorted by total points then total wins.
         *     Includes `tieRank: true` when the entry's record matches the previous entry.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Regular season leaderboard entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegularLeaderboardEntry"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-time transaction leaderboard
         * @description Returns each team's total claim, drop, and trade counts with a per-season breakdown.
         *     Trade totals count distinct team participations by `season + occurred_at`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction leaderboard entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionLeaderboardEntry"][];
                    };
                };
                /** @description Missing or invalid API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Team: {
            /** @example 1 */
            id: string;
            /** @example colorado */
            name: string;
            /** @example Colorado Avalanche */
            presentName: string;
            nameAliases?: string[];
            /**
             * @description First season year (YYYY) for expansion/relocated teams.
             * @example 2017
             */
            firstSeason?: number;
        };
        Season: {
            /** @example 2023 */
            season: number;
            /** @example 2023-2024 */
            text: string;
        };
        CountSplit: {
            owned: number;
            played: number;
        };
        CareerSummaryTeam: {
            teamId: string;
            teamName: string;
            seasonCount: components["schemas"]["CountSplit"];
            firstSeason: number;
            lastSeason: number;
        };
        CareerSummary: {
            firstSeason: number;
            lastSeason: number;
            seasonCount: components["schemas"]["CountSplit"];
            teamCount: components["schemas"]["CountSplit"];
            teams: components["schemas"]["CareerSummaryTeam"][];
        };
        CareerPlayerStatsLine: {
            games: number;
            goals: number;
            assists: number;
            points: number;
            plusMinus: number;
            penalties: number;
            shots: number;
            ppp: number;
            shp: number;
            hits: number;
            blocks: number;
        };
        CareerGoalieStatsLine: {
            games: number;
            wins: number;
            saves: number;
            shutouts: number;
            goals: number;
            assists: number;
            points: number;
            penalties: number;
            ppp: number;
            shp: number;
        };
        CareerPlayerTeamTotals: components["schemas"]["CareerPlayerStatsLine"] & {
            teamId: string;
            teamName: string;
            seasonCount: components["schemas"]["CountSplit"];
        };
        CareerGoalieTeamTotals: components["schemas"]["CareerGoalieStatsLine"] & {
            teamId: string;
            teamName: string;
            seasonCount: components["schemas"]["CountSplit"];
        };
        CareerPlayerTotals: components["schemas"]["CareerPlayerStatsLine"] & {
            seasonCount: components["schemas"]["CountSplit"];
            teamCount: components["schemas"]["CountSplit"];
            teams: components["schemas"]["CareerPlayerTeamTotals"][];
        };
        CareerGoalieTotals: components["schemas"]["CareerGoalieStatsLine"] & {
            seasonCount: components["schemas"]["CountSplit"];
            teamCount: components["schemas"]["CountSplit"];
            teams: components["schemas"]["CareerGoalieTeamTotals"][];
        };
        CareerPlayerSeason: components["schemas"]["CareerPlayerStatsLine"] & {
            season: number;
            /** @enum {string} */
            reportType: "regular" | "playoffs";
            teamId: string;
            teamName: string;
            position: string;
        };
        CareerGoalieSeason: components["schemas"]["CareerGoalieStatsLine"] & {
            season: number;
            /** @enum {string} */
            reportType: "regular" | "playoffs";
            teamId: string;
            teamName: string;
            /** @description Omitted when source data only contains a zero placeholder. */
            gaa?: string;
            /** @description Omitted when source data only contains a zero placeholder. */
            savePercent?: string;
        };
        CareerPlayer: {
            id: string;
            name: string;
            position: string;
            summary: components["schemas"]["CareerSummary"];
            totals: {
                career: components["schemas"]["CareerPlayerTotals"];
                regular: components["schemas"]["CareerPlayerTotals"];
                playoffs: components["schemas"]["CareerPlayerTotals"];
            };
            seasons: components["schemas"]["CareerPlayerSeason"][];
        };
        CareerPlayerListItem: {
            id: string;
            name: string;
            position: string;
            firstSeason: number;
            lastSeason: number;
            seasonsOwned: number;
            seasonsPlayedRegular: number;
            seasonsPlayedPlayoffs: number;
            teamsOwned: number;
            teamsPlayedRegular: number;
            teamsPlayedPlayoffs: number;
            regularGames: number;
            playoffGames: number;
        };
        CareerGoalieListItem: {
            id: string;
            name: string;
            firstSeason: number;
            lastSeason: number;
            seasonsOwned: number;
            seasonsPlayedRegular: number;
            seasonsPlayedPlayoffs: number;
            teamsOwned: number;
            teamsPlayedRegular: number;
            teamsPlayedPlayoffs: number;
            regularGames: number;
            playoffGames: number;
        };
        /** @enum {string} */
        CareerHighlightType: "most-teams-played" | "most-teams-owned" | "same-team-seasons-played" | "same-team-seasons-owned" | "most-stanley-cups" | "reunion-king" | "stash-king" | "regular-grinder-without-playoffs";
        CareerHighlightTeam: {
            id: string;
            name: string;
        };
        CareerTeamCountHighlightItem: {
            id: string;
            name: string;
            position: string;
            teamCount: number;
            teams: components["schemas"]["CareerHighlightTeam"][];
        };
        CareerSameTeamHighlightItem: {
            id: string;
            name: string;
            position: string;
            seasonCount: number;
            team: components["schemas"]["CareerHighlightTeam"];
        };
        CareerStanleyCupHighlightCup: {
            season: number;
            team: components["schemas"]["CareerHighlightTeam"];
        };
        CareerStanleyCupHighlightItem: {
            id: string;
            name: string;
            position: string;
            cupCount: number;
            cups: components["schemas"]["CareerStanleyCupHighlightCup"][];
        };
        CareerReunionHighlightItem: {
            id: string;
            name: string;
            position: string;
            reunionCount: number;
            team: components["schemas"]["CareerHighlightTeam"];
            stints: components["schemas"]["CareerReunionHighlightStint"][];
        };
        CareerReunionHighlightStint: {
            fromSeason: number;
            toSeason: number;
        };
        CareerStashHighlightItem: {
            id: string;
            name: string;
            position: string;
            seasonCount: number;
            team: components["schemas"]["CareerHighlightTeam"];
        };
        CareerRegularGrinderHighlightItem: {
            id: string;
            name: string;
            position: string;
            regularGames: number;
            teams: components["schemas"]["CareerHighlightTeam"][];
        };
        CareerTeamCountHighlightPage: {
            /** @enum {string} */
            type: "most-teams-played" | "most-teams-owned";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerTeamCountHighlightItem"][];
        };
        CareerSameTeamHighlightPage: {
            /** @enum {string} */
            type: "same-team-seasons-played" | "same-team-seasons-owned";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerSameTeamHighlightItem"][];
        };
        CareerStanleyCupHighlightPage: {
            /** @enum {string} */
            type: "most-stanley-cups";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerStanleyCupHighlightItem"][];
        };
        CareerReunionHighlightPage: {
            /** @enum {string} */
            type: "reunion-king";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerReunionHighlightItem"][];
        };
        CareerStashHighlightPage: {
            /** @enum {string} */
            type: "stash-king";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerStashHighlightItem"][];
        };
        CareerRegularGrinderHighlightPage: {
            /** @enum {string} */
            type: "regular-grinder-without-playoffs";
            skip: number;
            take: number;
            total: number;
            items: components["schemas"]["CareerRegularGrinderHighlightItem"][];
        };
        CareerGoalie: {
            id: string;
            name: string;
            summary: components["schemas"]["CareerSummary"];
            totals: {
                career: components["schemas"]["CareerGoalieTotals"];
                regular: components["schemas"]["CareerGoalieTotals"];
                playoffs: components["schemas"]["CareerGoalieTotals"];
            };
            seasons: components["schemas"]["CareerGoalieSeason"][];
        };
        Player: {
            name: string;
            /** @description Fantrax player identifier extracted from `*id*` in CSV name field. */
            id: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            plusMinus: number;
            penalties: number;
            shots: number;
            ppp: number;
            shp: number;
            hits: number;
            blocks: number;
            /** @description Composite score (0-100 range). */
            score: number;
            /** @description Stabilized per-game pace score. */
            scoreAdjustedByGames: number;
            /** @description Per-stat score breakdown. */
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            /** @description Stabilized per-game pace score compared to the same position only. */
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        Goalie: {
            name: string;
            /** @description Fantrax goalie identifier extracted from `*id*` in CSV name field. */
            id: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            penalties: number;
            ppp: number;
            shp: number;
            wins: number;
            saves: number;
            shutouts: number;
            /** @description Goals against average. Omitted for `reportType=both` or when source data only contains a zero placeholder. */
            gaa?: string;
            /** @description Save percentage. Omitted for `reportType=both` or when source data only contains a zero placeholder. */
            savePercent?: string;
            score: number;
            /** @description Stabilized per-game pace score. */
            scoreAdjustedByGames: number;
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            /** @description Stabilized per-game pace score compared to the same position only. */
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        /** @description Per-season row nested under `CombinedPlayer.seasons`. Omits `name` because the combined root object already includes it. */
        PlayerSeasonData: {
            season: number;
            /** @description Fantrax player identifier extracted from `*id*` in CSV name field. */
            id: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            plusMinus: number;
            penalties: number;
            shots: number;
            ppp: number;
            shp: number;
            hits: number;
            blocks: number;
            score: number;
            /** @description Stabilized per-game pace score. */
            scoreAdjustedByGames: number;
            /** @description Per-stat score breakdown. */
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            /** @description Stabilized per-game pace score compared to the same position only. */
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        /** @description Per-season row nested under `CombinedGoalie.seasons`. Omits `name` because the combined root object already includes it. */
        GoalieSeasonData: {
            season: number;
            /** @description Fantrax goalie identifier extracted from `*id*` in CSV name field. */
            id: string;
            position?: string;
            games: number;
            goals: number;
            assists: number;
            points: number;
            penalties: number;
            ppp: number;
            shp: number;
            wins: number;
            saves: number;
            shutouts: number;
            /** @description Goals against average. Omitted for `reportType=both` or when source data only contains a zero placeholder. */
            gaa?: string;
            /** @description Save percentage. Omitted for `reportType=both` or when source data only contains a zero placeholder. */
            savePercent?: string;
            score: number;
            /** @description Stabilized per-game pace score. */
            scoreAdjustedByGames: number;
            scores?: {
                [key: string]: number;
            };
            scoreByPosition?: number;
            /** @description Stabilized per-game pace score compared to the same position only. */
            scoreByPositionAdjustedByGames?: number;
            scoresByPosition?: {
                [key: string]: number;
            };
        };
        CombinedPlayer: components["schemas"]["Player"] & {
            seasons: components["schemas"]["PlayerSeasonData"][];
        };
        CombinedGoalie: components["schemas"]["Goalie"] & {
            seasons: components["schemas"]["GoalieSeasonData"][];
        };
        PlayoffLeaderboardEntry: {
            teamId: string;
            teamName: string;
            /** @description Total playoff appearances (sum of championships, finals, conferenceFinals, secondRound, and firstRound). */
            appearances: number;
            championships: number;
            finals: number;
            conferenceFinals: number;
            secondRound: number;
            firstRound: number;
            seasons: components["schemas"]["PlayoffLeaderboardSeason"][];
            /** @description True when this entry's record matches the previous entry's record. */
            tieRank: boolean;
        };
        PlayoffLeaderboardSeason: {
            season: number;
            /** @description Playoff round reached: 0=not qualified, 1-4=round reached, 5=championship. */
            round: number;
            /** @enum {string} */
            key: "championship" | "final" | "conferenceFinal" | "secondRound" | "firstRound" | "notQualified";
        };
        RegularLeaderboardEntry: {
            teamId: string;
            teamName: string;
            seasons: components["schemas"]["RegularLeaderboardSeason"][];
            wins: number;
            losses: number;
            ties: number;
            points: number;
            divWins: number;
            divLosses: number;
            divTies: number;
            winPercent: number;
            divWinPercent: number;
            /** @description Achieved points as a fraction of the maximum possible points (wins×2 + ties) / (games×2). */
            pointsPercent: number;
            /** @description Number of seasons the team finished rank 1 in regular standings. */
            regularTrophies: number;
            /** @description True when this entry's record matches the previous entry's record. */
            tieRank: boolean;
        };
        RegularLeaderboardSeason: {
            season: number;
            regularTrophy: boolean;
            wins: number;
            losses: number;
            ties: number;
            points: number;
            divWins: number;
            divLosses: number;
            divTies: number;
            winPercent: number;
            divWinPercent: number;
            pointsPercent: number;
        };
        TransactionLeaderboardEntry: {
            teamId: string;
            teamName: string;
            claims: number;
            drops: number;
            /** @description Count of distinct trade participations by `season + occurred_at`. */
            trades: number;
            seasons: components["schemas"]["TransactionLeaderboardSeason"][];
            /** @description True when this entry's record matches the previous entry's record. */
            tieRank: boolean;
        };
        TransactionLeaderboardSeason: {
            season: number;
            claims: number;
            drops: number;
            /** @description Count of distinct trade participations by `season + occurred_at`. */
            trades: number;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description Report dataset. `regular` and `playoffs` return the corresponding
         *     dataset. `both` merges regular + playoffs stats then calculates scores.
         */
        reportType: "regular" | "playoffs" | "both";
        /** @description Starting year of the season in YYYY format (e.g. `2023` for 2023-2024). */
        season: number;
        /** @description Team identifier. Defaults to `1` (repo maintainer's team). IDs are defined in `constants.ts`. */
        teamId: string;
        /**
         * @description Filter results to start from this season (inclusive). Starting year in YYYY format.
         *     Works with `/seasons`, `/players/combined/*`, and `/goalies/combined/*`.
         */
        startFrom: number;
        /** @description Number of rows to skip from the start of the sorted highlight list. Defaults to `0`. */
        skip: number;
        /** @description Number of rows to return from the sorted highlight list. Defaults to `10`. Maximum `100`. */
        take: number;
        /** @description Fantrax player or goalie identifier. */
        careerId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
